local_backend: true
backend:
  name: git-gateway
  branch: main

# media_folder: "public/images"
# public_folder: "/images" 
folder: "src/content/gallery"

allow_multiple: true
media_library:
  name: cloudinary
  config:
    multiple: "true"
    cloud_name: ddsddw7ua
    api_key: 813753631294118
    # default_transformations:
        # - - effect: grayscale


collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/content/gallery"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Category Title", name: "title", widget: "string" }
      - { label: "Alternative Image Title", name: "alt", widget: "string" }
      - { label: "Category Detail", name: "detail", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - label: "Images"
        name: "images"
        widget: "image"
        choose_url: false