# local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "/images/small-photographer-portfolio"
public_folder: "/images/small-photographer-portfolio" 
folder: "src/content/gallery"

allow_multiple: true
media_library:
  name: cloudinary
  config:
    multiple: "true"
    cloud_name: ddsddw7ua
    api_key: 813753631294118
    upload_preset: "small-photographer-portfolio"
    default_transformations:
    - - fetch_format: auto
        quality: auto
        # - - effect: grayscale


collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/content/gallery"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Category Title", name: "title", widget: "string" }
      - { label: "Alternative Image Title", name: "alt", widget: "string" }
      - { label: "Category Detail", name: "detail", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - label: "Images"
        name: "images"
        widget: "image"
        choose_url: false